name: CI/CD
on:
  push:
    branches:
      - production
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and run tests
        run: mvn clean test
  build:
    name: Build
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and install
        run: mvn clean install
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          # Vytvoření pouze pro ARM64 platformu
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.YOUR_APP }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.YOUR_APP }}:latest
  deploy:
    name: Deploy
    needs: [ test, build ]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Kubernetes Connection
        run: |
          kubectl get nodes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/metallb-config.yaml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
